!Apocalypse.Any.Domain.Server.Configuration.Model.GameServerConfiguration,%20Apocalypse.Any.Domain.Server.Configuration.Model,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
RedisHost: 
RedisPort: 6379
SectorConfigurations:
  - BuildOperation: BuildDefaultSectorState
    CurrentStatus: Uninitialized
    MaxEnemies: 16
    MaxPlayers: 4
    Routes: null
    RunOperation: RunAsDefaultSector
    SectorBoundaries: !Apocalypse.Any.Domain.Server.Model.SectorBoundary,%20Apocalypse.Any.Domain.Server.Model,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
      MaxSectorX: 16000
      MaxSectorY: 16000
      MinSectorX: 0
      MinSectorY: 0
    StartupFunction: Main
    StartupScript: H:\Code\apocalypse_github\apocalypse.echse
    Tag: hub
SerializationAdapterType: Apocalypse.Any.Infrastructure.Common.Services.Serializer.MsgPackAdapter.MsgPackSerializerAdapter
ServerIp: 127.0.0.1
ServerPeerName: asteroid
ServerPort: 8080
ServerUpdateInSeconds: 0.0099999997764825821
StartingSector: hub
