!Apocalypse.Any.Domain.Server.Model.GameServerConfiguration,%20Apocalypse.Any.Domain.Server.Model,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
BuildOperation: BuildDefaultSectorState
RunOperation: RunAsDefaultSector
MaxEnemies: 16
MaxPlayers: 4
RedisHost: 
RedisPort: 0
SerializationAdapterType: Apocalypse.Any.Infrastructure.Common.Services.Serializer.MsgPackAdapter.MsgPackSerializerAdapter
ServerIp: 127.0.0.1
ServerPeerName: asteroid
ServerPort: 8080
ServerUpdateInSeconds: 0.0099999997764825821
StartingSector: 0
StartupFunction: Main
StartupScript: 'H:/Code/apocalypse_github/apocalypse.echse'
SectorXSize: 16000
SectorYSize: 16000