!Apocalypse.Any.Domain.Client.Model.GameClientConfiguration,%2520Apocalypse.Any.Domain.Client.Model,%2520Version=1.0.0.0,%2520Culture=neutral,%2520PublicKeyToken=null
Background:
  AsteroidsCount: 1300
  DebrisFieldCount: 1500
  StarsFieldCount: 2000
Screen:
  ScreenHeight: 768
  ScreenWidth: 1024
ServerIp: 127.0.0.1
ServerPeerName: asteroid
SerializationAdapterType: Apocalypse.Any.Infrastructure.Common.Services.Serializer.MsgPackAdapter.MsgPackSerializerAdapter
ServerPort: 8080
User:
  Username: foo3
  Password: 12345
